### ISSUE TITLE
Tweets with Images Don't Fit

### ISSUE THREAD

**Issue by joshvickerson** [zachleat/bernie-tweets#1]
Tried putting in one of my tweets with an image and, well, it didn't quite fit.

[This is the tweet I tried.](https://www.zachleat.com/bernie/joshvickerson/817930473435439104)

**Comment by zachleat** [comment]
Hmm, I want to keep the vertical centering. But top aligning only big tweets might be a challenge, unless I use JS I guess. I’m already using it to position the tweet.

**Comment by joshvickerson** [comment]
If you use the oembed API it'll be possible to fully customize the tweet's appearance. So you could simply hide media attachments or do something clever with it if you'd like.

[Link to the docs](https://dev.twitter.com/rest/reference/get/statuses/oembed), for convenience.

**Comment by zachleat** [comment]
Not quite the best readability, but this works “good enough” for now:
* https://www.zachleat.com/bernie/6track/742867384495546368
* https://www.zachleat.com/bernie/joshvickerson/817930473435439104
