### ISSUE TITLE
Using the input box produces an invalid URL

### ISSUE THREAD

**Issue by itsrainy** [zachleat/bernie-tweets#2]
If you paste a tweet URL into the input box, the URL that gets created is missing the `/bernie/` part from the path. Consequently, sharing the URL results in users visiting this beautiful page:

![image](https://cloud.githubusercontent.com/assets/844493/21812091/cf013f02-d71f-11e6-9216-df6b75020c7f.png)

**Comment by zachleat** [comment]
@jcox92 Thank you for reporting that! Fixed now
